CREATE TABLE "mytable" (
  "Yes. Here are the **answers only**" text,
  "with **the same headings and question numbers** as in your file." text NULL
);

INSERT INTO "mytable" ("Yes. Here are the **answers only**","with **the same headings and question numbers** as in your file.")
VALUES
('```sql',NULL),
('###############################################################',NULL),
('###############################################################',NULL),
('-- Guided Project: SQL CASE Statements',NULL),
('###############################################################',NULL),
('###############################################################',NULL),
('#############################',NULL),
('-- Task One: The SQL CASE Statement',NULL),
('#############################',NULL),
('-- 1.1: Retrieve all the data in the employees table',NULL),
('SELECT *',NULL),
('FROM employees;',NULL),
('-- 1.2: Change M to Male and F to Female in the employees table',NULL),
('SELECT',NULL),
('emp_no',NULL),
('first_name',NULL),
('last_name',NULL),
('CASE',NULL),
('WHEN gender = ''M'' THEN ''Male''',NULL),
('ELSE ''Female''',NULL),
('END AS gender',NULL),
('FROM employees;',NULL),
('-- 1.3: This gives the same result as 1.2',NULL),
('SELECT',NULL),
('emp_no',NULL),
('first_name',NULL),
('last_name',NULL),
('CASE gender',NULL),
('WHEN ''M'' THEN ''Male''',NULL),
('WHEN ''F'' THEN ''Female''',NULL),
('END AS gender',NULL),
('FROM employees;',NULL),
('-- 1.4: This gives the same result as 1.2 & 1.3',NULL),
('SELECT',NULL),
('emp_no',NULL),
('first_name',NULL),
('last_name',NULL),
('IF(gender = ''M''','''Male'''),
('FROM employees;',NULL),
('#############################',NULL),
('-- Task Two: Adding multiple conditions to a CASE statement',NULL),
('#############################',NULL),
('-- 2.1: Retrieve all the data in the customers table',NULL),
('SELECT *',NULL),
('FROM customers;',NULL),
('-- 2.2: Create a column called Age_Category',NULL),
('SELECT',NULL),
('*',NULL),
('CASE',NULL),
('WHEN age < 30 THEN ''Young''',NULL),
('WHEN age > 60 THEN ''Aged''',NULL),
('ELSE ''Middle Aged''',NULL),
('END AS Age_Category',NULL),
('FROM customers;',NULL),
('-- 2.3: Retrieve a list of employees...',NULL),
('SELECT',NULL),
('emp_no',NULL),
('first_name',NULL),
('last_name',NULL),
('hire_date',NULL),
('CASE',NULL),
('WHEN hire_date < ''1990-01-01'' THEN ''Employed before 1990''',NULL),
('WHEN hire_date BETWEEN ''1990-01-01'' AND ''1995-12-31''',NULL),
('THEN ''Employed between 1990 and 1995''',NULL),
('ELSE ''Employed after 1995''',NULL),
('END AS hire_category',NULL),
('FROM employees;',NULL),
('#############################',NULL),
('-- Task Three: The CASE Statement and Aggregate Functions',NULL),
('#############################',NULL),
('-- 3.1: Retrieve the average salary of all employees',NULL),
('SELECT',NULL),
('emp_no',NULL),
('AVG(salary) AS average_salary',NULL),
('FROM salaries',NULL),
('GROUP BY emp_no',NULL),
('ORDER BY average_salary DESC;',NULL),
('-- 3.2',NULL),
('SELECT',NULL),
('emp_no',NULL),
('AVG(salary) AS average_salary',NULL),
('CASE',NULL),
('WHEN AVG(salary) > 80000 THEN ''Paid Well''',NULL),
('WHEN AVG(salary) < 80000 THEN ''Underpaid''',NULL),
('ELSE ''Unpaid''',NULL),
('END AS salary_status',NULL),
('FROM salaries',NULL),
('GROUP BY emp_no;',NULL),
('-- 3.3',NULL),
('SELECT',NULL),
('emp_no',NULL),
('AVG(salary) AS average_salary',NULL),
('CASE',NULL),
('WHEN AVG(salary) > 80000',NULL),
('AND AVG(salary) < 100000 THEN ''Paid Well''',NULL),
('WHEN AVG(salary) < 80000 THEN ''Underpaid''',NULL),
('ELSE ''Manager''',NULL),
('END AS salary_status',NULL),
('FROM salaries',NULL),
('GROUP BY emp_no;',NULL),
('-- 3.4: Count the number of employees in each salary category',NULL),
('SELECT',NULL),
('salary_status',NULL),
('COUNT(*) AS total',NULL),
('FROM',NULL),
('(',NULL),
('SELECT',NULL),
('emp_no',NULL),
('CASE',NULL),
('WHEN AVG(salary) > 80000',NULL),
('AND AVG(salary) < 100000 THEN ''Paid Well''',NULL),
('WHEN AVG(salary) < 80000 THEN ''Underpaid''',NULL),
('ELSE ''Manager''',NULL),
('END AS salary_status',NULL),
('FROM salaries',NULL),
('GROUP BY emp_no',NULL),
(') a',NULL),
('GROUP BY salary_status;',NULL),
('#############################',NULL),
('-- Task Four: The CASE Statement and SQL Joins',NULL),
('#############################',NULL),
('-- 4.1: Retrieve all the data from the employees and dept_manager tables',NULL),
('SELECT *',NULL),
('FROM employees',NULL),
('ORDER BY emp_no DESC;',NULL),
('SELECT *',NULL),
('FROM dept_manager;',NULL),
('-- 4.2: Join all the records in the employees table to the dept_manager table',NULL),
('SELECT',NULL),
('e.emp_no',NULL),
('dm.emp_no',NULL),
('e.first_name',NULL),
('e.last_name',NULL),
('FROM employees e',NULL),
('LEFT JOIN dept_manager dm',NULL),
('ON e.emp_no = dm.emp_no',NULL),
('ORDER BY dm.emp_no;',NULL),
('-- 4.3',NULL),
('SELECT',NULL),
('e.emp_no',NULL),
('dm.emp_no',NULL),
('e.first_name',NULL),
('e.last_name',NULL),
('FROM employees e',NULL),
('LEFT JOIN dept_manager dm',NULL),
('ON e.emp_no = dm.emp_no',NULL),
('WHERE e.emp_no > 109990;',NULL),
('-- 4.4',NULL),
('SELECT',NULL),
('e.emp_no',NULL),
('e.first_name',NULL),
('e.last_name',NULL),
('CASE',NULL),
('WHEN dm.emp_no IS NOT NULL THEN ''Manager''',NULL),
('ELSE ''Employee''',NULL),
('END AS is_manager',NULL),
('FROM employees e',NULL),
('LEFT JOIN dept_manager dm',NULL),
('ON e.emp_no = dm.emp_no;',NULL),
('-- 4.5',NULL),
('SELECT',NULL),
('e.emp_no',NULL),
('e.first_name',NULL),
('e.last_name',NULL),
('CASE',NULL),
('WHEN dm.emp_no IS NOT NULL THEN ''Manager''',NULL),
('ELSE ''Employee''',NULL),
('END AS is_manager',NULL),
('FROM employees e',NULL),
('LEFT JOIN dept_manager dm',NULL),
('ON e.emp_no = dm.emp_no',NULL),
('WHERE e.emp_no > 109990;',NULL),
('#############################',NULL),
('-- Task Five: The CASE Statement together with Aggregate Functions and Joins',NULL),
('#############################',NULL),
('-- 5.1: Retrieve all the data from the employees and salaries tables',NULL),
('SELECT *',NULL),
('FROM employees;',NULL),
('SELECT *',NULL),
('FROM salaries;',NULL),
('-- 5.2: Retrieve a list of all salaries earned by an employee',NULL),
('SELECT',NULL),
('e.emp_no',NULL),
('e.first_name',NULL),
('e.last_name',NULL),
('s.salary',NULL),
('FROM employees e',NULL),
('JOIN salaries s',NULL),
('ON e.emp_no = s.emp_no;',NULL),
('-- 5.3',NULL),
('SELECT',NULL),
('e.emp_no',NULL),
('e.first_name',NULL),
('e.last_name',NULL),
('MAX(s.salary) - MIN(s.salary) AS salary_difference',NULL),
('CASE',NULL),
('WHEN MAX(s.salary) - MIN(s.salary) > 30000',NULL),
('THEN ''Salary was raised by more than $30','000'''),
('WHEN MAX(s.salary) - MIN(s.salary) BETWEEN 20000 AND 30000',NULL),
('THEN ''Salary was raised by more than $20','000 but less than $30'),
('ELSE ''Salary was raised by less than $20','000'''),
('END AS salary_increase',NULL),
('FROM employees e',NULL),
('JOIN salaries s',NULL),
('ON e.emp_no = s.emp_no',NULL),
('GROUP BY',NULL),
('e.emp_no',NULL),
('e.first_name',NULL),
('e.last_name;',NULL),
('-- 5.4: Retrieve all the data from the employees and dept_emp tables',NULL),
('SELECT *',NULL),
('FROM employees;',NULL),
('SELECT *',NULL),
('FROM dept_emp;',NULL),
('-- 5.5',NULL),
('SELECT',NULL),
('e.emp_no',NULL),
('e.first_name',NULL),
('e.last_name',NULL),
('CASE',NULL),
('WHEN MAX(de.to_date) = ''9999-01-01'' THEN ''Is still employed''',NULL),
('ELSE ''Not an employee anymore''',NULL),
('END AS current_employee',NULL),
('FROM employees e',NULL),
('JOIN dept_emp de',NULL),
('ON e.emp_no = de.emp_no',NULL),
('GROUP BY',NULL),
('e.emp_no',NULL),
('e.first_name',NULL),
('e.last_name',NULL),
('ORDER BY e.emp_no',NULL),
('LIMIT 100;',NULL),
('#############################',NULL),
('-- Task Six: Transposing data using the CASE clause',NULL),
('#############################',NULL),
('-- 6.1: Retrieve all the data from the sales table',NULL),
('SELECT *',NULL),
('FROM sales;',NULL),
('-- 6.2: Retrieve the count of the different profit_category from the sales table',NULL),
('SELECT',NULL),
('profit_category',NULL),
('COUNT(*) AS total',NULL),
('FROM',NULL),
('(',NULL),
('SELECT',NULL),
('order_line',NULL),
('profit',NULL),
('CASE',NULL),
('WHEN profit < 0 THEN ''No Profit''',NULL),
('WHEN profit > 0 AND profit < 500 THEN ''Low Profit''',NULL),
('WHEN profit > 500 AND profit < 1500 THEN ''Good Profit''',NULL),
('ELSE ''High Profit''',NULL),
('END AS profit_category',NULL),
('FROM sales',NULL),
(') a',NULL),
('GROUP BY profit_category;',NULL),
('-- 6.3: Transpose 6.2 above',NULL),
('SELECT',NULL),
('SUM(CASE WHEN profit < 0 THEN 1 ELSE 0 END) AS no_profit',NULL),
('SUM(CASE WHEN profit > 0 AND profit < 500 THEN 1 ELSE 0 END) AS low_profit',NULL),
('SUM(CASE WHEN profit > 500 AND profit < 1500 THEN 1 ELSE 0 END) AS good_profit',NULL),
('SUM(CASE WHEN profit >= 1500 THEN 1 ELSE 0 END) AS high_profit',NULL),
('FROM sales;',NULL),
('-- 6.4: Retrieve the number of employees in the first four departments in the dept_emp table',NULL),
('SELECT',NULL),
('dept_no',NULL),
('COUNT(*)',NULL),
('FROM dept_emp',NULL),
('WHERE dept_no IN (''d001''','''d002'''),
('GROUP BY dept_no',NULL),
('ORDER BY dept_no;',NULL),
('-- 6.5: Transpose 6.4 above',NULL),
('SELECT',NULL),
('SUM(CASE WHEN dept_no = ''d001'' THEN 1 ELSE 0 END) AS d001',NULL),
('SUM(CASE WHEN dept_no = ''d002'' THEN 1 ELSE 0 END) AS d002',NULL),
('SUM(CASE WHEN dept_no = ''d003'' THEN 1 ELSE 0 END) AS d003',NULL),
('SUM(CASE WHEN dept_no = ''d004'' THEN 1 ELSE 0 END) AS d004',NULL),
('FROM dept_emp;',NULL),
('```',NULL);
